### ISSUE TITLE
Django Analyst Number and Cybertech search

### ISSUE THREAD

**Issue by puneet-zalios** [puneet-zalios/wrangler#6]
See if a search can be done by Cybertech Analyst Number. Currently one can only search based on NC4/Everbridge Analyst Number.

![image](https://user-images.githubusercontent.com/4380481/97025776-60ef8480-150d-11eb-8346-20a02a8ad667.png)

**Comment by puneet-zalios** [comment]
@divick Added DB schema here
https://github.com/puneet-zalios/wrangler/tree/master/DBSchema

**Comment by divick** [comment]
@puneet-zalios ok. Thanks

**Comment by puneet-zalios** [comment]
@divick this ticket is not needed
